### ISSUE TITLE
DPXC Editor startet nicht

### ISSUE THREAD

**Issue by cboulanger** [notesjor/corpusexplorer2.0#15]
**Describe the bug**
Der DPXC Editor startet nicht (DPXC Editor ist installiert, getestet auf zwei unterschiedlichen Maschinen)

**To Reproduce**
CE starten, "Korpus Übersicht", "Korpus manuell erstellen" 

**Expected behavior**
DPXC Editor sollte starten 

**Actual behavior**
Auf dem einen PC passiert gar nichts, auf dem anderen kann man im Task Manager mehrere laufende Prozesse sehen, zwei CE-Hintergrundprozesse (Installer und Terminal.Winform) sowie ein DPXC-HIntergrundprozess (auch nach 10 Minuten keine Änderung). Wenn man den einen oder anderen Prozess beendet, passiert auch nichts. 

**Desktop (please complete the following information):**
Windows 10 Enterprise, Version 1809/21H2

**Comment by notesjor** [comment]
Danke für den Hinweis. Bitte probieren Sie einmal folgendes:

(siehe Screenshot)
1. Starten Sie die Windows-Suche über das Startmenü.
2. Geben Sie dpxc-editor ein.
3. Es sollte der DPXC-Editor erscheinen. Bitte auswählen. Startet dieser? - Im Task-Manager sichtbar?
![screen](https://user-images.githubusercontent.com/13318171/189767359-50610a21-71d3-498a-b9d4-857e6cfd9829.png)

(alternativ)
1. WINDOWS-Taste + R drücken
2. Ausführen erscheint. Hier bitte dpxc-editor.exe eintragen und ENTER drücken.

Wenn beide Wege nicht zum Ziel führen und der DPXC-Editor im Task-Manager bei 20-30 MB herumdümpelt, dann ist er vermutlich durch den Virenscanner blockiert. Bitte wenn möglich auf Ausnahme/Whitelist setzen.

**Comment by cboulanger** [comment]
Alles klar - es ist so, wie Sie es beschreiben, der DPXC-Editor erscheint als Hintergrundprozess mit 0% CPU und 28MB Arbeitsspeicher, aber weiter passiert nichts. Ich habe keine Adminrechte für die betroffenen Rechner und kann daher auch keine Ausnahme für den Virenscanner einfügen. Ich warte auf das Update. Danke!

**Comment by notesjor** [comment]
Das Problem wurde mit dem letzten Update behoben. Bei Rückfragen gerne erneut melden.

Wichtig: Der DPXC-Editor startet nur schneller, wenn er über den CorpusExplorer aufgerufen wird. Ein schnellerer Start für den separaten DPXC-Prozess ist in Arbeit.
