### ISSUE TITLE
Korpusverteilung/Neue Metaangabe funktioniert nicht

### ISSUE THREAD

**Issue by cboulanger** [notesjor/corpusexplorer2.0#16]
**Describe the bug**

Führt man Korpusverteilung -> Bearbeiten -> Neue Metaangabe aus, arbeitet CE eine Weile, aber es wird keine neue Spalte mit einer Metaangabe hinzugefügt oder angezeigt. 

**Desktop (please complete the following information):**
Windows 10 Enterprise (auf zwei verschiedenen Maschinen getestet)

**Comment by notesjor** [comment]
Vielen Dank für den Hinweis. Das Problem wird mit dem nächsten Update behoben. Voraussichtlich in 1-2 Wochen. Falls es dringend ist, mit eine Nachricht schreiben (https://notes.jan-oliver-ruediger.de/kontakt/), dann schicke ich ein privates Patch/Update.

**Comment by notesjor** [comment]
Das Problem wurde mit dem letzten Update behoben. Bei Rückfragen gerne erneut melden.
