### ISSUE TITLE
Fehler bein Laden eines vorhandenen Projekts nach letztem Update

### ISSUE THREAD

**Issue by ariMssieW** [notesjor/corpusexplorer2.0#30]
**FEHLERREPORT:** 
21.02.2023 16:12:57
TargetInvocationException
Ein Aufrufziel hat einen Ausnahmefehler verursacht.
   bei System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   bei System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   bei System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   bei CorpusExplorer.Sdk.Model.Project.Load(String path, String forceCorpusRoot)
   bei CorpusExplorer.Sdk.Terminal.TerminalController.ProjectLoad(String path, String forceCorpusRoot)
   bei CorpusExplorer.Terminal.WinForm.Forms.Dashboard.Dashboard.ProjectLoad(String path)
   bei Telerik.WinControls.RadElement.OnClick(EventArgs e)
   bei Telerik.WinControls.UI.RadMenuItem.OnClick(EventArgs e)
   bei Telerik.WinControls.RadElement.DoClick(EventArgs e)
   bei Telerik.WinControls.RadElement.RaiseBubbleEvent(RadElement sender, RoutedEventArgs args)
   bei Telerik.WinControls.RadItem.RaiseBubbleEvent(RadElement sender, RoutedEventArgs args)
   bei Telerik.WinControls.RadElement.RaiseRoutedEvent(RadElement sender, RoutedEventArgs args)
   bei Telerik.WinControls.ComponentInputBehavior.OnMouseUp(MouseEventArgs e)
   bei Telerik.WinControls.RadControl.OnMouseUp(MouseEventArgs e)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei Telerik.WinControls.RadControl.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>>>
DirectoryNotFoundException
Ein Teil des Pfades "C:\Users\TXPadmin\Documents\CorpusExplorer\Meine Korpora\Bachelorarbeit Whataboutism Korpus.cec6.lz4" konnte nicht gefunden werden.
>	   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   bei CorpusExplorer.Sdk.Model.Adapter.Corpus.CorpusAdapterWriteDirect.CreateLz4(String path)
---

**To Reproduce**
1. Go to Projekt laden
2. Click on wanted program
3. See error

**Expected behavior**
That the project opens

**Update:**
CorpusExplorer (Update Q1 2023) – SP1

**Comment by notesjor** [comment]
Hallo, vielen Dank für den Fehlerbericht. So wie es aussieht, ist das Problem nicht auf das Update zurückzuführen. Anscheinend haben Sie das Korpus "C:\Users\TXPadmin\Documents\CorpusExplorer\Meine Korpora\Bachelorarbeit Whataboutism Korpus.cec6.lz4" verschoben oder gelöscht. Wenn ich das richtig verstanden habe, wurde ein Projekt geladen, das dieses Korpus referenziert. Projekte bündeln (referenzieren) mehrere Korpora, speichern diese aber aus Platzgründen nicht doppelt. Ein weiterer Grund für das Löschen/Verschieben könnte sein, dass Sie ein anderes Benutzerkonto oder einen anderen Computer verwenden und nicht alle Dateien kopiert haben. Bitte stellen Sie sicher, dass alle Dateien/Ordner kopiert wurden. Diese befinden sich im Ordner C:\Users\TXPadmin\Documents\CorpusExplorer\ - Projekte befinden sich im Unterordner "Meine Projekte" Korpora im Ordner "Meine Korpora". 
Bei weiteren Fragen und/oder Problemen können Sie mich auch gerne direkt per E-Mail kontaktieren:
https://notes.jan-oliver-ruediger.de/kontakt/ (E-Mail Adresse steht oben auf der Seite).

Konsequenzen:
- Beim nächsten Update werde ich die Fehlermeldung besser gestalten/formulieren.
- Ich werde in einem kommenden Update berücksichtigen, dass Projekte auch dann laden wenn der Windows-Benutzername ein anderer ist.
- Da diese Meldung nicht funktioniert, schließe ich den Fall. Bitte per E-Mail melden.
