### ISSUE TITLE
Asking for an English version

### ISSUE THREAD

**Issue by David-Csy** [notesjor/corpusexplorer2.0#31]
Dear Jan Oliver Rüdiger,

CorpusExplorer is a significantly powerful tool for corpus research. Could you please make an English version of your powerful software? Thanks a lot!

Sincerely,
David Cui

**Comment by notesjor** [comment]
Dear David Cui,
I hope a english version is comming soon (long time feature request). If you are familar with the CMD (and don't need the GUI), you can use the CorpusExplorerConsole https://github.com/notesjor/CorpusExplorer.Terminal.Console - the console is available in english and german (Download and install the CorpusExplorer: https://www.bitcutstudios.com/products/CorpusExplorer/standard/publish.htm) and the cec command is available in your cmd-shell.
Best regards
Jan

I close this request - for any other questions please use my normal contact information:
https://notes.jan-oliver-ruediger.de/kontakt/
